import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import academicYearRoutes from './academicYear.routes';
import academicEventRoutes from './academicEvent.routes';
import majorRoutes from './major.routes';
import subjectRoutes from './subject.routes';
import classRoutes from './class.routes';
import publicRoutes from './public.routes';
import trainingClassRoutes from './trainingClass.routes';
import workProgramRoutes from './workProgram.routes';
import extracurricularRoutes from './extracurricular.routes';
import uploadRoutes from './upload.routes';
import teacherAssignmentRoutes from './teacherAssignment.routes';
import exportImportRoutes from './exportImport.routes';
import attendanceRoutes from './attendance.routes';
import scheduleRoutes from './schedule.routes';
import scheduleTimeConfigRoutes from './scheduleTimeConfig.routes';
import reportRoutes from './report.routes';
import budgetRequestRoutes from './budgetRequest.routes';
import gradeRoutes from './grade.routes';
import assignmentRoutes from './assignment.routes';
import materialRoutes from './material.routes';
import submissionRoutes from './submission.routes';
import examRoutes from './exam.routes';
import examSittingRoutes from './exam-sitting.routes';
import proctorRoutes from './proctor.routes';
import notificationRoutes from './notification.routes';
import cpTpAnalysisRoutes from './cpTpAnalysis.routes';
import ukkSchemeRoutes from './ukkScheme.routes';
import ukkAssessmentRoutes from './ukkAssessment.routes';
import behaviorRoutes from './behavior.routes';
import permissionRoutes from './permission.routes';
import subjectCategoryRoutes from './subjectCategory.routes';
import tutorRoutes from './tutor.routes';
import studentExtracurricularRoutes from './studentExtracurricular.routes';
import internshipRoutes from './internship.routes';
import humasRoutes from './humas.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/academic-years', academicYearRoutes);
router.use('/academic-events', academicEventRoutes);
router.use('/majors', majorRoutes);
router.use('/subjects', subjectRoutes);
router.use('/classes', classRoutes);
router.use('/public', publicRoutes);
router.use('/training-classes', trainingClassRoutes);
router.use('/work-programs', workProgramRoutes);
router.use('/extracurriculars', extracurricularRoutes);
router.use('/upload', uploadRoutes);
router.use('/teacher-assignments', teacherAssignmentRoutes);
router.use('/data', exportImportRoutes);
router.use('/attendances', attendanceRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/schedule-time-configs', scheduleTimeConfigRoutes);
router.use('/reports', reportRoutes);
router.use('/budget-requests', budgetRequestRoutes);
router.use('/grades', gradeRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/materials', materialRoutes);
router.use('/submissions', submissionRoutes);
router.use('/exams', examRoutes);
router.use('/exam-sittings', examSittingRoutes);
router.use('/proctoring', proctorRoutes);
router.use('/notifications', notificationRoutes);
router.use('/cp-tp-analyses', cpTpAnalysisRoutes);
router.use('/ukk-schemes', ukkSchemeRoutes);
router.use('/ukk-assessments', ukkAssessmentRoutes);
router.use('/behaviors', behaviorRoutes);
router.use('/permissions', permissionRoutes);
router.use('/subject-categories', subjectCategoryRoutes);
router.use('/tutor', tutorRoutes);
router.use('/student/extracurriculars', studentExtracurricularRoutes);
router.use('/internships', internshipRoutes);
router.use('/humas', humasRoutes);

export default router;
